// export const countryToCode: Record<string, string> = {
//   al: 'Albania',
//   at: 'Austria',
//   be: 'Belgium',
//   ba: 'Bosnia and Herzegovina',
//   bg: 'Bulgaria',
//   hr: 'Croatia',
//   cy: 'Cyprus',
//   cz: 'Czech Republic',
//   dk: 'Denmark',
//   ee: 'Estonia',
//   fi: 'Finland',
//   fr: 'France',
//   de: 'Germany',
//   gr: 'Greece',
//   hu: 'Hungary',
//   ie: 'Ireland',
//   il: 'Israel',
//   it: 'Italy',
//   jo: 'Jordan',
//   lv: 'Latvia',
//   lt: 'Lithuania',
//   lu: 'Luxembourg',
//   mt: 'Malta',
//   me: 'Montenegro',
//   ma: 'Morocco',
//   nl: 'Netherlands',
//   no: 'Norway',
//   pl: 'Poland',
//   pt: 'Portugal',
//   ro: 'Romania',
//   rs: 'Serbia',
//   sk: 'Slovakia',
//   es: 'Spain',
//   se: 'Sweden',
//   ch: 'Switzerland',
//   tr: 'Turkey',
//   gb: 'United Kingdom',
// };
